Tourmalet/config/routes.rb
Rails.application.routes.draw do

  # Root
  root to: 'studies#index'

  #devise_for :users
  devise_for :users, controllers: {sessions: "users/sessions"}
  resources :users, except: [:create] do
    member do
      put :update_name
      put :set_read
      put :set_edit
      put :set_system_admin
    end
  end
  post 'create_user' => 'users#create', as: :create_user

  # API
  namespace :api do
    namespace :v1 do
      resources :studies, only: [:index] do
        member do
          get :history
        end
        resources :study_versions, only: [:show] do
        end
      end
      resources :study_versions, only: [:show] do
        resources :forms, only: [:show]
      end
    end
  end

  # User Settings
  resources :user_settings

  resources :audit_trail, only: [:index] do
    collection do
      post :search
      get :export_csv
    end
  end

  # Tokens
  resources :tokens, only: [:index] do
    member do
      post :release
      get :status
      get :extend_token
    end
  end

  # Standard resources
  resources :amendments, only: [:update, :create, :destroy] do
    collection do
      get :find
    end
  end
  resources :studies, only: [:index, :new, :create, :destroy] do
    member do
      get :history
    end
  end
  match 'study_versions/:id/export' => 'study_versions#export', :via => [:get, :post]
  resources :study_versions, only: [:new, :create, :edit, :destroy, :show, :update] do
    member do
      get :status
      put :update_status
      get :soa
      put :clear
      get :export
      get :export_json
      get :export_odm
      get :export_als
      get :export_crf
      get :export_acrf
    end
    collection do
      post :export_crf
      post :export_acrf
    end
  end
  resources :forms do
    member do
      put 'move'
    end
  end
  resources :visits  do
    member do
      put 'move'
    end
  end
  resources :elements do
    collection do
      post 'toggle'
      get 'for_study'
      delete 'clear'
    end
  end
  resources :mdrs do
    collection do
      get 'forms_list'
      get 'forms_all'
      get 'forms'
      get 'form'
      get 'thesaurus_concept'
      get 'bc_property'
      get 'form_show'
      get 'form_annotations'
    end

  end
  namespace :mdrs do
    resources :forms, only: [] do
      member do
        get 'history'
        get 'latest'
      end
    end
  end
  resources :markdown_engines, only: [:create, :index]
end

Tourmalet/app/models/user.rb
class User < ActiveRecord::Base
  
  # Include the user settings
  include UserSettings
 
	# Constants
  C_CLASS_NAME = "User"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, # :validatable, 
    :timeoutable,
    :password_expirable, :password_archivable , :secure_validatable

  # Simple role / access level management
  enum access_level: [:read, :edit, :system_admin]

  after_create :set_extra
  after_save :user_update

  # Set any extra items we need when a user is created
  def set_extra
    # Set the reader default role.
    self.access_level = User.access_levels[:read]
  end

  # Do any processing after user is changed
  def user_update
    # Audit if password changed  
    if encrypted_password_changed?
      AuditTrail.user_event(self, "User changed password.")
    end
  end

  # Has Read access
  #
  # @return [Boolean] true if user has read access, false otherwise
  def has_read_access? 
  	self.read? || self.edit? || self.system_admin?
	end

  # Has Edit access
  #
  # @return [Boolean] true if user has edit access, false otherwise
  def has_edit_access? 
  	self.edit? || self.system_admin?
	end

  # Has System Admin access
  #
  # @return [Boolean] true if user has system admin access, false otherwise
  def has_system_admin_access? 
  	self.system_admin?
	end

	# Role List
  #
  # @return [String] the roles as a string
  def role_list
		return "Read" if self.read?
		return "Read, Edit" if self.edit?
		return "Read, Edit, System Admin" if self.system_admin?
		return "err!"
	end

end

Tourmalet/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  
  before_filter :log_logout, :only => :destroy  #add this at the top with the other filters
  # Lines commented out may be useful for other events, e.g. failed login attempt.
  #after_filter :log_failed_login, :only => [:new, :create]

  def create
    super
    AuditTrail.user_event(current_user, "User logged in.")
  end
 
 private
 
  #def log_failed_login
  #end

  #def failed_login?
  #  (options = env["warden.options"]) && options[:action] == "unauthenticated"
  #end

  def log_logout
    AuditTrail.user_event(current_user, "User logged out.")
  end

end

Tourmalet/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :authorized?
  before_action :set_user, only: [:show, :edit, :update_name, :update_access_level]

  C_CLASS_NAME = "UsersController"
  
  def new
  end

  def set_read
    user = User.find(params[:id])
    current_roles = user.role_list
    if last_system_admin?(user)
      flash[:error] = "You cannot remove system admin access from your user account. You are the last system admin user!"
    else
      user.read!
      AuditTrail.update_event(current_user, "User #{user.email} roles updated from [#{current_roles}] to [#{user.role_list}].")
    end
    redirect_to users_path
  end

  def set_edit
    user = User.find(params[:id])
    current_roles = user.role_list
    if last_system_admin?(user)
      flash[:error] = "You cannot remove system admin access from your user account. You are the last system admin user!"
    else
      user.edit!
      AuditTrail.update_event(current_user, "User #{user.email} roles updated from [#{current_roles}] to [#{user.role_list}].")
    end
    redirect_to users_path
  end
  
  def set_system_admin
    user = User.find(params[:id])
    current_roles = user.role_list
    user.system_admin!
    AuditTrail.update_event(current_user, "User #{user.email} roles updated from [#{current_roles}] to [#{user.role_list}].")
    redirect_to users_path
  end

  def create
    new_user = User.create(user_params)
    if new_user.errors.blank?
      AuditTrail.create_event(current_user, "User #{new_user.email} created.")
      flash[:success] = "User was successfully created."
    else
      flash[:error] = "User was not created. #{new_user.errors.full_messages.to_sentence}."
    end
    redirect_to users_path
  end  

  def index
    @users = User.all.order("name ASC")
  end

  def show
  end

  def edit
  end

  def update_name
    if @user.update(user_params)
      flash[:success] = "User display name sucessfully updated."
    else
      flash[:error] = "Failed to update user display name."
    end
    redirect_to user_settings_path
  end

  def destroy
    # Note, no check on deleting the last admin user as cannot delete yourself and
    # you need to be admin to delete.
    user = User.find(params[:id])
    delete_email = user.email
    if current_user.id != user.id 
      user.destroy
      AuditTrail.delete_event(current_user, "User #{delete_email} deleted.")
      flash[:success] = "User #{delete_email} was successfully deleted."  
    else
      flash[:error] = "You cannot delete your own user!"
    end
    redirect_to users_path
  end

private

  def authorized?
    authorize User
  end

  def last_system_admin?(user)
    return user.id == current_user.id && current_user.has_system_admin_access? && system_admin_user_count == 1
  end

  def system_admin_user_count
    users = User.where(access_level: User.access_levels[:system_admin])
    return users.count
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :access_level, :name)
  end

end

Tourmalet/app/views/users/edit.html.erb
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Current Settings: <%= @user.name %> (<%= @user.email %>)</h4>
      </div>
      <div class="panel-body">
        <p>There are set number of role combinations. They can be set using the buttons to the right.</p>
    		<table id="user_info" class="table table-striped table-condensed">
          <tbody>
          	<tr>
              <td><strong>Email:</strong></td><td><%= @user.email %></td>
            </tr>
            <tr>
              <td><strong>Display Name:</strong></td><td><%= @user.name %></td>
            </tr>
            <tr>
              <td><strong>Current Roles:</strong></td><td><%= @user.role_list %></td>
            </tr>
            <tr>
              <td><strong>Login Count:</strong></td><td><%= @user.sign_in_count %></td>
            </tr>
          </tbody>
        </table>
        <%= link_to "Close", users_path, :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
	<div class="col-md-4">
		<div class="panel panel-success">
			<div class="panel-heading"><h4 class="panel-title">Reader Role</h4></div>
  		<div class="panel-body">
    		<p>The lowest level of access. Reader access permits the user to have read-only access to the MDR's content.</p>
    		<%= link_to "Set Read Role", set_read_user_path(@user), id: "read_button", method: :put, :class => "btn btn-success btn-block" %>
  		</div>
		</div>
		<div class="panel panel-success">
			<div class="panel-heading"><h4 class="panel-title">Editor Role</h4></div>
  		<div class="panel-body">
    		<p>The next level of access up from the reader. editor access permits the user to have view access to the MDR's content while also being able to edit the content.</p>
    		<%= link_to "Set Edit Role", set_edit_user_path(@user), id: "edit_button", method: :put, :class => "btn btn-success btn-block" %>
  		</div>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-warning">
			<div class="panel-heading"><h4 class="panel-title">Read, Edit & System Admin Role</h4></div>
  		<div class="panel-body">
    		<p>This access sets the read and edit role along with additional system administration rights.</p>
    		<%= link_to "Set Read, Edit & System Admin Role", set_system_admin_user_path(@user), id: "system_admin_button", method: :put, :class => "btn btn-warning btn-block" %>
  		</div>
		</div>
	</div>
</div>

Tourmalet/app/views/users/index.html.erb
<%= javascript_include_tag 'standard_datatable' %>
<div class="row">
	<div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">User & Role Management</h3>
      </div>
      <div class="panel-body">
        <table id="main" class="table table-striped table-bordered table-condensed">
          <thead>
            <tr>
                <th>Email</th>
                <th>Display Name</th>
                <th>Access Level</th>
                <th></th>
                <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= user.email %></td>
                <td><%= user.name %></td>
                <td><%= user.role_list %></td>
                <td><%= link_to "Edit", edit_user_path(user), :class => "btn btn-primary btn-xs" %></td>
                <td>
                  <% if current_user.id != user.id %>
                    <%= link_to "Delete", user_path(user), :class => "btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure?" } %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to "New", new_user_path, id: "new_user_button", :class => "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

Tourmalet/app/views/users/new.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New User</h3>
      </div>
      <div class="panel-body">
        <%= form_for User.new, url: create_user_path do |f| %>
          <div class="form-group">
            <%= f.label :email, "Email:" %><br />
            <%= f.email_field :email, class: "form-control", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.label :name, "Display Name:" %><br />
            <%= f.text_field :name, class: "form-control", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.label :password, "Password:" %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, class: "form-control", autocomplete: "off" %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, "Password Confirmation:" %><br />
            <%= f.password_field :password_confirmation, class: "form-control", autocomplete: "off" %>
          </div>
          <%= f.submit "Create", id: "create_button", class: "btn btn-primary" %>
          <%= link_to "Close", users_path, id: "close_button", :class => "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>