Tourmalet/config/routes.rb
Rails.application.routes.draw do

  # Root
  root to: 'studies#index'

  #devise_for :users
  devise_for :users, controllers: {sessions: "users/sessions"}
  resources :users, except: [:create] do
    member do
      put :update_name
      put :set_read
      put :set_edit
      put :set_system_admin
    end
  end
  post 'create_user' => 'users#create', as: :create_user

  # API
  namespace :api do
    namespace :v1 do
      resources :studies, only: [:index] do
        member do
          get :history
        end
        resources :study_versions, only: [:show] do
        end
      end
      resources :study_versions, only: [:show] do
        resources :forms, only: [:show]
      end
    end
  end

  # User Settings
  resources :user_settings

  resources :audit_trail, only: [:index] do
    collection do
      post :search
      get :export_csv
    end
  end

  # Tokens
  resources :tokens, only: [:index] do
    member do
      post :release
      get :status
      get :extend_token
    end
  end

  # Standard resources
  resources :amendments, only: [:update, :create, :destroy] do
    collection do
      get :find
    end
  end
  resources :studies, only: [:index, :new, :create, :destroy] do
    member do
      get :history
    end
  end
  match 'study_versions/:id/export' => 'study_versions#export', :via => [:get, :post]
  resources :study_versions, only: [:new, :create, :edit, :destroy, :show, :update] do
    member do
      get :status
      put :update_status
      get :soa
      put :clear
      get :export
      get :export_json
      get :export_odm
      get :export_als
      get :export_crf
      get :export_acrf
    end
    collection do
      post :export_crf
      post :export_acrf
    end
  end
  resources :forms do
    member do
      put 'move'
    end
  end
  resources :visits  do
    member do
      put 'move'
    end
  end
  resources :elements do
    collection do
      post 'toggle'
      get 'for_study'
      delete 'clear'
    end
  end
  resources :mdrs do
    collection do
      get 'forms_list'
      get 'forms_all'
      get 'forms'
      get 'form'
      get 'thesaurus_concept'
      get 'bc_property'
      get 'form_show'
      get 'form_annotations'
    end

  end
  namespace :mdrs do
    resources :forms, only: [] do
      member do
        get 'history'
        get 'latest'
      end
    end
  end
  resources :markdown_engines, only: [:create, :index]
end

Tourmalet/app/models/audit_trail.rb
require 'csv'

class AuditTrail < ActiveRecord::Base

	enum event_type: {empty_action: 0, create_action: 1, update_action: 2, delete_action: 3, user_action: 4}

	@@event_string_map = ["", "Create", "Update", "Delete", "User"]

	# Event To String. Human readbale lable for the event
	#
	# @return [string] The label
	def event_to_s
		return @@event_string_map[self.event]
	end

	# Event To String. Human readbale lable for the event
	#
	# @param index [integer] Index of the event
	# @return [string] The label
	def self.event_to_s(index)
		@@event_string_map[index].nil? ? result = "" : result = @@event_string_map[index]
		return result
	end

	# Create Item Event. Log creation of an item
	#
	# @param user [object] The user object
	# @param identifier [object] The identifier
	# @param version [object] The version
	# @param description [string] The description
	# @return null
	def self.create_item_event(user, identifier, version, description)
		add_item(user, identifier, version, event_types[:create_action], description)
	end

	# Update Item Event. Log update of an item
	#
	# @param user [object] The user object
	# @param identifier [object] The identifier
	# @param version [object] The version
	# @param description [string] The description
	# @return null
	def self.update_item_event(user, identifier, version, description)
		add_item(user, identifier, version, event_types[:update_action], description)
	end

	# Delete Item Event. Log deletion of an item
	#
	# @param user [object] The user object
	# @param identifier [object] The identifier
	# @param version [object] The version
	# @param description [string] The description
	# @return null
	def self.delete_item_event(user, identifier, version, description)
		add_item(user, identifier, version, event_types[:delete_action], description)
	end

	# Create Event. Log a creation event (generic)
	#
	# @param user [object] The user object
	# @param decscirption [string] The description
	# @return null
	def self.create_event(user, description)
		add_generic(user, event_types[:create_action], description)
	end

	# Update Event. Log a creation event (generic)
	#
	# @param user [object] The user object
	# @param decscirption [string] The description
	# @return null
	def self.update_event(user, description)
		add_generic(user, event_types[:update_action], description)
	end

	# Delete Event. Log a creation event (generic)
	#
	# @param user [object] The user object
	# @param decscirption [string] The description
	# @return null
	def self.delete_event(user, description)
		add_generic(user, event_types[:delete_action], description)
	end

	# User Event. Log a user event
	#
	# @param user [object] The user object
	# @param decscirption [string] The description
	# @return null
	def self.user_event(user, description)
		add_generic(user, event_types[:user_action], description)
	end

	# To CSV
  #
  # @return [Object] the CSV serialization
  def self.to_csv
  	items = AuditTrail.all
    csv_data = CSV.generate do |csv|
      csv << ["Date Time", "User", "Identifier", "Version", "Event", "Details"]
      items.each do |item|
        csv << [Timestamp.new(item.date_time).to_datetime, item.user, item.identifier, item.version, item.event_to_s, item.description]
      end
    end
    return csv_data
  end

private

	def self.add_item(user, identifier, version, event, description)
		self.create(date_time: Time.now, user: user.email, identifier: identifier, version: version, event: event, description: description)
	end

	def self.add_generic(user, event, description)
		self.create(date_time: Time.now, user: user.email, identifier: "", version: "", event: event, description: description)
	end

end

Tourmalet/app/controllers/audit_trail_controller.rb
class AuditTrailController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_audit_trail, only: [:show, :edit, :update, :destroy]
  
  C_CLASS_NAME = "AuditTrailsController"
  C_RECORDS = 2000

  def index
    authorize AuditTrail
    @items = AuditTrail.last(C_RECORDS)
    @defaults = {:user => "", :identifier => "", :owner => "", :event => AuditTrail.event_types[:empty_action]}
    users_owners_events
  end

  def search
    authorize AuditTrail
    param_set = the_params
    remove_key(param_set, :user, "")
    remove_key(param_set, :identifier, "")
    remove_key(param_set, :owner, "")
    remove_key(param_set, :event, AuditTrail.event_types[:empty_action].to_s)
    @items = AuditTrail.where(param_set).all
    @defaults = the_params
    users_owners_events
    render "index"
  end

  def export_csv
    authorize AuditTrail
    send_data AuditTrail.to_csv, filename: "audit_trail.csv", :type => 'text/csv; charset=utf-8; header=present', disposition: "attachment"
  end

private

  def set_audit_trail
    @audit_trail = AuditTrail.find(params[:id])
  end

  def the_params
    params.require(:audit_trail).permit(:user, :identifier, :owner, :event)
  end

  def users_owners_events
    @users = User.all
    @users.unshift(User.new)
    @events = AuditTrail.event_types
  end

  def remove_key(params, key, value)
    if params[key] == value
      params.delete key
    end
  end

end

Tourmalet/app/helpers/audit_trails_helper.rb
module AuditTrailsHelper
end

Tourmalet/app/views/audit_trail/index.html.erb
<%= javascript_include_tag 'standard_datatable' %>
<div id="datatables_order">
  <!-- Datatables column order option-->
  <%= javascript_tag "var dtMainOrderUpdate = #{column_order(0, :desc)};" %>
</div>
<div class="row">
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">Audit Trail</h4>
      </div>
      <div class="panel-body">
        <table id="main" class="table table-striped table-bordered table-condensed">
            <thead>
            <tr>
                <th class="col-sm-2">Date Time</th>
                <th class="col-sm-2">User</th>
                <th class="col-sm-1">Identifier</th>
                <th class="col-sm-1">Version</th>
                <th class="col-sm-1">Event</th>
                <th class="col-sm-4">Details</th>
              </tr>
          </thead>
          <tbody>
            <% @items.each do |item| %>
                <tr>
                  <td><%= Timestamp.new(item.date_time).to_datetime %></td>
                  <td><%= item.user %></td>
                  <td><%= item.identifier %></td>
                  <td><%= item.version %></td>
                  <td><%= item.event_to_s %></td>
                  <td><%= item.description %></td>
                </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to "All", audit_trail_index_path, id: "all_button", :class => "btn btn-primary" %>
        <%= link_to "Export CSV", export_csv_audit_trail_index_path, id: "export_csv_button", :class => "btn btn-info" %>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title">Search</h3>
      </div>
      <div class="panel-body">
        <%= form_for AuditTrail.new, :url => search_audit_trail_index_path do |f| %>
          <div class="form-group">
              <%= f.label :user, "User:" %><br />
              <%= f.select(:user, options_for_select(@users.map{ |u| [u.email, u.email]}, @defaults[:user]), {}, {:class => 'form-control'}) %>
          </div>
          <div class="form-group">
              <%= f.label :identifier, "Identifier:" %><br />
              <%= f.text_field :identifier, class: "form-control" %>
          </div>
          <div class="form-group">
              <%= f.label :event, "Event:" %><br />
              <%= f.select(:event, options_for_select(@events.map{ |key, u| [AuditTrail.event_to_s(u), u]}, @defaults[:event]), {}, {:class => 'form-control'}) %>
          </div>
          <%= f.submit "Submit", class: "btn btn-default btn-primary" %>          
        <% end %>
      </div>
    </div>
  </div>
</div>