Tourmalet/config/routes.rb
Rails.application.routes.draw do

  # Root
  root to: 'studies#index'

  #devise_for :users
  devise_for :users, controllers: {sessions: "users/sessions"}
  resources :users, except: [:create] do
    member do
      put :update_name
      put :set_read
      put :set_edit
      put :set_system_admin
    end
  end
  post 'create_user' => 'users#create', as: :create_user

  # API
  namespace :api do
    namespace :v1 do
      resources :studies, only: [:index] do
        member do
          get :history
        end
        resources :study_versions, only: [:show] do
        end
      end
      resources :study_versions, only: [:show] do
        resources :forms, only: [:show]
      end
    end
  end

  # User Settings
  resources :user_settings

  resources :audit_trail, only: [:index] do
    collection do
      post :search
      get :export_csv
    end
  end

  # Tokens
  resources :tokens, only: [:index] do
    member do
      post :release
      get :status
      get :extend_token
    end
  end

  # Standard resources
  resources :amendments, only: [:update, :create, :destroy] do
    collection do
      get :find
    end
  end
  resources :studies, only: [:index, :new, :create, :destroy] do
    member do
      get :history
    end
  end
  match 'study_versions/:id/export' => 'study_versions#export', :via => [:get, :post]
  resources :study_versions, only: [:new, :create, :edit, :destroy, :show, :update] do
    member do
      get :status
      put :update_status
      get :soa
      put :clear
      get :export
      get :export_json
      get :export_odm
      get :export_als
      get :export_crf
      get :export_acrf
    end
    collection do
      post :export_crf
      post :export_acrf
    end
  end
  resources :forms do
    member do
      put 'move'
    end
  end
  resources :visits  do
    member do
      put 'move'
    end
  end
  resources :elements do
    collection do
      post 'toggle'
      get 'for_study'
      delete 'clear'
    end
  end
  resources :mdrs do
    collection do
      get 'forms_list'
      get 'forms_all'
      get 'forms'
      get 'form'
      get 'thesaurus_concept'
      get 'bc_property'
      get 'form_show'
      get 'form_annotations'
    end

  end
  namespace :mdrs do
    resources :forms, only: [] do
      member do
        get 'history'
        get 'latest'
      end
    end
  end
  resources :markdown_engines, only: [:create, :index]
end

Tourmalet/app/models/study.rb
class Study < ActiveRecord::Base

	C_CLASS_NAME = "Study"

	has_many :study_versions, :dependent => :destroy

	validates :identifier, presence: true, uniqueness: true
  validates_presence_of :label

  def to_hash
  	return { id: self.id, identifier: self.identifier, label: self.label }
  end

end

Tourmalet/app/controllers/api/v1/studies_controller.rb
class Api::V1::StudiesController < ActionController::Base
  
  http_basic_authenticate_with name: ENV["api_username"], password: ENV["api_password"]

	C_CLASS_NAME = "Api:V1:StudyController"

  def index
    results = []
    studies = Study.all
    studies.each {|x| results << x.to_hash}
    render json: results, status: 200
  end

  def history
    study = Study.find_by_id(params[:id])
    if !study.nil?
    	results = []
	    study_versions = StudyVersion.where(study_id: params[:id]).order('version asc')
	    study_versions.each {|x| results << x.to_hash}
    	render json: results, status: 200
    else
    	render json: {errors: study_not_found_error}, status: 404
    end
  end

private 

  def study_not_found_error
		study = Study.new
    study.errors.add(:base, "Failed to find study with identifier #{params[:id]}")
    return study.errors.full_messages
  end
    	
end

Tourmalet/app/controllers/studies_controller.rb
class StudiesController < ApplicationController

  before_action :authenticate_user!
  before_action :authorized?

  TBS = "To be set"

  def index
  	@studies = Study.all
	end

	def history
    @study = Study.find(params[:id])
    token = Token.find_token(@study.identifier, current_user)
    token.release if !token.nil?
    @study_versions = StudyVersion.where(study_id: params[:id]).order('version asc')
    if @study_versions.count == 0 
      study_version = StudyVersion.create(study_id: params[:id], state: StudyVersion.states[:incomplete], 
        semantic_version: "0.1.0", version: 1, name: @study.label, description: TBS, protocol_name: TBS)
      AuditTrail.update_item_event(current_user, @study.identifier, study_version.semantic_version, "Study version created.")
      @study_versions = StudyVersion.where(study_id: params[:id])
    end
  end

  def create
		study = Study.create(the_params)
    if study.errors.empty?
      AuditTrail.update_item_event(current_user, study.identifier, "", "Study created.")
      redirect_to studies_path
    else
      flash[:error] = study.errors.full_messages.to_sentence
      redirect_to new_study_path
    end
	end

  def destroy
    study = Study.find(params[:id])
    study.destroy
    AuditTrail.update_item_event(current_user, study.identifier, "", "Study deleted.")
    redirect_to studies_path
  end

private

	def authorized?
    authorize Study
  end

  def the_params
  	params.require(:study).permit(:identifier, :label)
	end  	

end

Tourmalet/app/views/studies/history.html.erb
<%= javascript_include_tag 'standard_datatable' %>
<div class="row">
	<div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Study History: <%= @study.label %></h3>
      </div>
      <div class="panel-body">
        <table id="main" class="table table-striped table-bordered table-condensed">
          <thead>
            <tr>
                <th>Version</th>
                <th>Name</th>
                <th>Description</th>
                <th>Protocol Name</th>
                <th>State</th>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
          </thead>
          <tbody>
            <% @study_versions.each do |version| %>
              <tr>
                <td><%= version.semantic_version %></td>
                <td><%= version.name %></td>
                <td><%= version.description %></td>
                <td><%= version.protocol_name %></td>
                <td><%= version.state_label %></td>
                <td>
                  <%= link_to "View", study_version_path(version), :class => "btn btn-primary btn-xs" %>
                </td>
                <td>
                  <% if policy(StudyVersion).edit? && version == @study_versions.last %>
                    <%= link_to "Edit", edit_study_version_path(version), :class => "btn btn-primary btn-xs" %>
                  <% end %>
                </td>
                <td>
                  <% if policy(StudyVersion).status? && version == @study_versions.last %>
                    <%= link_to "Status", status_study_version_path(version), :class => "btn btn-primary btn-xs" %>
                  <% end %>
                </td>
                <td>
                  <% if policy(StudyVersion).destroy? %>
                    <% if version.delete? %>
                      <%= link_to "Delete", study_version_path(version), :class => "btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure?" }  %>
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to "Close", studies_path, id: "close_button", :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

Tourmalet/app/views/studies/index.html.erb
<%= javascript_include_tag 'standard_datatable' %>
<div class="row">
	<div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Studies</h3>
      </div>
      <div class="panel-body">
        <table id="main" class="table table-striped table-bordered table-condensed">
          <thead>
            <tr>
                <th>Identifier</th>
                <th>Label</th>
                <th></th>
                <th></th>
            </tr>
          </thead>
          <tbody>
            <% @studies.each do |study| %>
              <tr>
                <td><%= study.identifier %></td>
                <td><%= study.label %></td>
                <td><%= link_to "History", history_study_path(study), :class => "btn btn-primary btn-xs" %></td>
                <td>
                  <%= link_to "Delete", study_path(study), :class => "btn btn-danger btn-xs", method: :delete, data: { confirm: "Are you sure?" } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to "New", new_study_path, id: "new_study_button", :class => "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

Tourmalet/app/views/studies/new.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">New Study</h3>
      </div>
      <div class="panel-body">
        <%= form_for Study.new do |f| %>
          <div class="form-group">
            <%= f.label :identifier, "Identifier:" %><br />
            <%= f.text_field :identifier, class: "form-control", autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.label :label, "Useful Label:" %><br />
            <%= f.text_field :label, class: "form-control", autofocus: true %>
          </div>
          <%= f.submit "Create", id: "create_button", class: "btn btn-primary" %>
          <%= link_to "Close", studies_path, id: "close_button", :class => "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>