Tourmalet/config/routes.rb
Rails.application.routes.draw do

  # Root
  root to: 'studies#index'

  #devise_for :users
  devise_for :users, controllers: {sessions: "users/sessions"}
  resources :users, except: [:create] do
    member do
      put :update_name
      put :set_read
      put :set_edit
      put :set_system_admin
    end
  end
  post 'create_user' => 'users#create', as: :create_user

  # API
  namespace :api do
    namespace :v1 do
      resources :studies, only: [:index] do
        member do
          get :history
        end
        resources :study_versions, only: [:show] do
        end
      end
      resources :study_versions, only: [:show] do
        resources :forms, only: [:show]
      end
    end
  end

  # User Settings
  resources :user_settings

  resources :audit_trail, only: [:index] do
    collection do
      post :search
      get :export_csv
    end
  end

  # Tokens
  resources :tokens, only: [:index] do
    member do
      post :release
      get :status
      get :extend_token
    end
  end

  # Standard resources
  resources :amendments, only: [:update, :create, :destroy] do
    collection do
      get :find
    end
  end
  resources :studies, only: [:index, :new, :create, :destroy] do
    member do
      get :history
    end
  end
  match 'study_versions/:id/export' => 'study_versions#export', :via => [:get, :post]
  resources :study_versions, only: [:new, :create, :edit, :destroy, :show, :update] do
    member do
      get :status
      put :update_status
      get :soa
      put :clear
      get :export
      get :export_json
      get :export_odm
      get :export_als
      get :export_crf
      get :export_acrf
    end
    collection do
      post :export_crf
      post :export_acrf
    end
  end
  resources :forms do
    member do
      put 'move'
    end
  end
  resources :visits  do
    member do
      put 'move'
    end
  end
  resources :elements do
    collection do
      post 'toggle'
      get 'for_study'
      delete 'clear'
    end
  end
  resources :mdrs do
    collection do
      get 'forms_list'
      get 'forms_all'
      get 'forms'
      get 'form'
      get 'thesaurus_concept'
      get 'bc_property'
      get 'form_show'
      get 'form_annotations'
    end

  end
  namespace :mdrs do
    resources :forms, only: [] do
      member do
        get 'history'
        get 'latest'
      end
    end
  end
  resources :markdown_engines, only: [:create, :index]
end

Tourmalet/app/models/concerns/user_settings.rb
module UserSettings
  
  # Simple Setting Moduel

  extend ActiveSupport::Concern

  # Constants
  C_CLASS_NAME = "UserSettings"

  # Include for the user class. Sets up the properties. Defined within a configuration file.
  # This could be made better such that config parameters do not need to be 'known' but it 
  # will do for now
  included do
    has_many :user_settings, :dependent => :destroy
    # User settings
    user_hash = APP_CONFIG['user_settings']
    @@settings_metadata = user_hash.deep_symbolize_keys
    @@settings = {}
    @@settings_metadata.each do |key, hash|
      @@settings[key.to_sym] = hash[:default_value]
    end
  end

  # Add class methods
  module ClassMethods
  
    # Allows a setting to have the default value set  
    def setting(name, default)
      settings = self.class_variable_get(:'@@settings')
      settings[name] = default
      self.class_variable_set(:'@@settings', settings)
    end
  
  end

  # Return the settings
  #
  # @return [hash] Hash of the setting values
  def settings
    results = Hash.new
    @@settings_metadata.each do |key, setting|
      result = read_setting(key)
      results[key] = result.value
    end  
    return results
  end

  # Return the datatable settings
  #
  # @return [String] contains settings for datatables initialization
  def self.datatable_settings
    return "[[5,10,25,50,100,-1], [\"5\",\"10\",\"25\",\"50\",\"100\",\"All\"]]" if !@@settings_metadata.has_key?(:table_rows)
    info = @@settings_metadata[:table_rows][:values]
    values = info.map{|l,v| v}.join(",")
    labels = info.map{|l,v| "\"#{l}\""}.join(",")
    return "[[#{values}], [#{labels}]]"
  end

  # Clear and reset the settings metadata. Only used for testing
  #
  # @return [Null]
  if Rails.env == "test"
    
    def self.clear_settings_metadata
      @@settings_metadata = {}
    end

    def self.reset_settings_metadata
      user_hash = APP_CONFIG['user_settings']
      @@settings_metadata = user_hash.deep_symbolize_keys
      @@settings = {}
      @@settings_metadata.each do |key, hash|
        @@settings[key.to_sym] = hash[:default_value]
      end 
    end

  end

  # Return the settings metadata
  #
  # @return [hash] Hash of the setting metadata
  def settings_metadata
    return @@settings_metadata
  end

  # Read a setting
  #
  # @param [string] 
  # @return [hash] The setting value or nil
  def read_setting(name)
    if p = self.user_settings.where(:name => name).first
      return p
    end
    return self.user_settings.new(:name => name, :value => @@settings[name]) if @@settings.has_key?(name)
    nil
  end

  # Write a setting
  #
  # @param name [string] The setting's name
  # @param value [string] the setting's value
  def write_setting(name, value)
    p = self.user_settings.where(name: name).first_or_create
    p.update(value: value)
  end

  # Handle missing method. Attempt to read or write the setting, otherwise will fail
  def method_missing(method, *args)
    if @@settings.keys.any?{|k| method =~ /#{k}/}
      if method =~ /=/
        self.write_setting(method.to_s.gsub('=', ''), *args)
      else
        p = self.read_setting(method)
        return p.value
      end
    else
      super
    end
  end

end

Tourmalet/app/models/user_setting.rb
class UserSetting < ActiveRecord::Base

	belongs_to :user

	validates_uniqueness_of :name, :scope => :user_id
	
end

Tourmalet/app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController

  before_action :authenticate_user!
  before_action :authorized?
  before_action :set_settings, only: [:index, :show, :edit, :update]
  
  C_CLASS_NAME = "UsersController"
  
  def index
    @settings_metadata = @user.settings_metadata
  end

  def update
    name = user_params[:name]
    value = user_params[:value]
    @user.write_setting(name, value)
    redirect_to user_settings_path
  end

private

  def authorized?
    authorize UserSetting
  end

  def set_settings
    @user = current_user
    @settings = @user.settings
  end

  def user_params
    params.require(:user_settings).permit(:name, :value)
  end

end

Tourmalet/app/views/user_settings/index.html.erb
<div class="row">
	<div class="col-md-9">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">Current Settings: <%= current_user.name %> (<%= current_user.email %>)</h4>
					</div>
		  		<div class="panel-body">
		    		<div class="row">
							<div class="col-md-6">
								<table id="user_info" class="table table-striped table-condensed">
									<tbody>
										<tr>
											<th class="col-md-4">Display Name:</th><td><%= current_user.name %></td>
										</tr>
										<tr>
											<th>Email:</th><td><%= current_user.email %></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<p>Your current settings are listed below. These may be changed by using the buttons to the right.</p>
								<% ordered_metadata = @settings_metadata.sort_by {|key, x| x[:label]} %>
								<table id="user_settings" class="table table-striped table-condensed">
									<tbody>
										<% ordered_metadata.each do |key, md| %>
											<tr>
									    	<th class="col-md-2"><%= md[:label] %>:</th>
									    	<td class="col-md-6"><%= md[:description] %></td>
									    	<% if md[:type] == "enum" %>
									    		<% md[:values].each do |option| %>
									    			<% if option == @settings[key] %>
									    				<td class="col-md-1">
									    			 		<%= link_to @settings[key], user_setting_path(:id => current_user.id, :user_settings => {:name => key, :value => option}), :method => :put, :class => "btn btn-success btn-xs" %>
									    			 	</td>
									    			<% end %>
									    		<% end %>
									    		<td class="col-md-3">
											  		<% md[:values].each do |option| %>
											  			<% if option != @settings[key] %>
											  			 	<%= link_to option, user_setting_path(:id => current_user.id, :user_settings => {:name => key, :value => option}), :method => :put, :class => "btn btn-primary btn-xs" %>
											  			<% end %>
											  		<% end %>
											  	</td>
									    	<% elsif md[:type] == "coded" %>
									    		<% md[:values].each do |value_key, option| %>
									    			<% if option.to_s == @settings[key] %>
									    				<td class="col-md-1">
									    					<%= link_to value_key, user_setting_path(:id => current_user.id, :user_settings => {:name => key, :value => option}), :method => :put, :class => "btn btn-success btn-xs" %>
									    			 	</td>
									    			<% end %>
									    		<% end %>
		  										<td class="col-md-3">
											  		<% md[:values].each do |value_key, option| %>
											  			<% if option.to_s != @settings[key] %>
											  			 		<%= link_to value_key, user_setting_path(:id => current_user.id, :user_settings => {:name => key, :value => option}), :method => :put, :class => "btn btn-primary btn-xs" %>
											  			<% end %>
											  		<% end %>
		  										</td>
									    	<% end %>
										  </tr>
										<% end %>
									</tbody>
								</table>
							</div>
						</div>
		  		</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-md-3">
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">Change Password</h4>
					</div>
		  		<div class="panel-body">
	  			  <%= form_for(current_user, url: registration_path(current_user), html: { method: :put }) do |f| %>
					    <div class="form-group">
					      <%= f.label :current_password, "Current Password:" %>
					      <%= f.password_field :current_password, autocomplete: "off", class: "form-control" %>
					    </div>
					    <div class="form-group">
					      <%= f.label :password, "New Password:" %>
					      <% if @minimum_password_length %>
					        <em>(<%= @minimum_password_length %> characters minimum)</em>
					      <% end %><br />
					      <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
					    </div>
					    <div class="form-group">
					      <%= f.label :password_confirmation, "Confirm New Password:" %>
					      <% if @minimum_password_length %>
					        <em>(<%= @minimum_password_length %> characters minimum)</em>
					      <% end %><br />
					      <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
					    </div>
					    <%= f.submit "Update", id: "password_update_button", class: "btn btn-default btn-primary" %>
					  <% end %>
		  		</div>
			  </div>
		  </div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h4 class="panel-title">Change Display Name</h4>
					</div>
		  		<div class="panel-body">
	  			  <%= form_for(current_user, url: update_name_user_path(current_user), html: { method: :put }) do |f| %>
					    <div class="form-group">
					      <%= f.label :name, "New Display Name:" %>
					      <%= f.text_field :name, class: "form-control" %>
					    </div>
					    <%= f.submit "Update", id: "name_update_button", class: "btn btn-default btn-primary" %>
					  <% end %>
		  		</div>
			  </div>
		  </div>
		</div>
	</div>
</div>